image: maven:3-jdk-8

build:
  stage: build
  script:
    - echo "building..."
    - "mvn clean"

integration_tests:
  stage: test
  script:
    - echo "running integration tests..."
    - "mvn install"
